apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kagent-httproute
  namespace: kagent
spec:
  parentRefs:
    - name: http-gateway
      namespace: kgateway-system
  rules:
  - matches:
    -  path:
        type: PathPrefix
        value: /
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacement: /
    backendRefs:
    - name: kagent-ui
      port: 80
