apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kagent-httproute
  namespace: kagent
spec:
  parentRefs:
    - name: http-gateway
      namespace: kgateway-system
  rules:
  - matches:
    -  path:
        type: PathPrefix
        value: /
        value: /kagent
    backendRefs:
    - name: kagent-ui
      port: 80
