apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: homelab-rules
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  groups:
    - name: system.rules
      rules:
        - alert: NodeDown
          expr: up == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.instance }} down"
            description: "Prometheus target {{ $labels.job }} on {{ $labels.instance }} is not responding."

        - alert: HighCPUUsage
          expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) > 85
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High CPU usage on {{ $labels.instance }}"
            description: "CPU usage > 85% for 5 minutes."

        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on {{ $labels.instance }}"
            description: "Memory usage > 90% for 5 minutes."

        - alert: DiskFilling
          expr: (node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"} - node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"}) / node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"} * 100 > 85
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Disk filling on {{ $labels.instance }} ({{ $labels.mountpoint }})"
            description: "Disk usage > 85% for 10 minutes."
