apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: unpoller
  namespaceSelector:
    matchNames: ["monitoring"]
  endpoints:
    - port: http-metrics
      interval: 30s
