apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    app: unpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpoller
  template:
    metadata:
      labels:
        app: unpoller
    spec:
      containers:
        - name: unpoller
          image: golift/unifi-poller:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9130
              name: metrics
          env:
            - name: UP_PROMETHEUS_HTTP_LISTEN
              value: ":9130"
            - name: UP_PROMETHEUS_ENABLE
              value: "true"
            - name: UP_UNIFI_URL
              valueFrom:
                secretKeyRef:
                  name: unpoller-secret
                  key: UNIFI_URL
            - name: UP_UNIFI_USER
              valueFrom:
                secretKeyRef:
                  name: unpoller-secret
                  key: UNIFI_USER
            - name: UP_UNIFI_PASS
              valueFrom:
                secretKeyRef:
                  name: unpoller-secret
                  key: UNIFI_PASS
            - name: UP_UNIFI_DEFAULT_SITE
              valueFrom:
                secretKeyRef:
                  name: unpoller-secret
                  key: UNIFI_DEFAULT_SITE
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: unpoller-config
            items:
              - key: up.conf
                path: up.conf
