apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller
  namespaceSelector:
    matchNames: [ "monitoring" ]
  endpoints:
    - port: metrics
      interval: 30s
