apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: unifi-alerts
  namespace: monitoring
spec:
  groups:
    - name: unifi.rules
      rules:
        - alert: UniFiGatewayDown
          expr: probe_success{probe="unifi-gateway"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "UniFi Gateway is unreachable"
            description: "The UniFi Gateway at 192.168.1.1 is not responding."

        - alert: DNSServersDown
          expr: probe_success{probe="dns-servers"} == 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "DNS servers unreachable"
            description: "One or more public DNS servers are failing ICMP probes."

        - alert: WebsiteDown
          expr: probe_success{probe="websites"} == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "External website down"
            description: "One of the monitored websites is failing HTTP checks."

