apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - storage.yaml
  - prometheus/
  - probes/
  - alerts/
  - grafana/
  - unifi/

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus
    namespace: monitoring
    valuesInline:
      grafana:
        enabled: true
        persistence:
          enabled: true
          type: pvc
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          size: 10Gi
          existingClaim: grafana-pvc
      prometheus:
        prometheusSpec:
          retention: 15d
          storageSpec:
            volumeClaimTemplate:
              metadata:
                name: prometheus-storage
              spec:
                storageClassName: ""
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 20Gi
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    valuesFile: loki-stack-values.yaml
  - name: prometheus-blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: blackbox
    namespace: monitoring
