apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ./unifi/namespace.yaml
  - ./unifi/unpoller-configmap.yaml
  - ./unifi/unpoller-deployment.yaml
  - ./unifi/unpoller-service.yaml
  - ./unifi/unpoller-servicemonitor.yaml
  - ./alerts
  - ./probes

configMapGenerator:
  - name: grafana-dash-unifi-11310
    files:
      - dashboards/unifi/unpoller-dashboard-11310.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dash-unifi-11311
    files:
      - dashboards/unifi/unpoller-dashboard-11311.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dash-unifi-11312
    files:
      - dashboards/unifi/unpoller-dashboard-11312.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dash-unifi-11313
    files:
      - dashboards/unifi/unpoller-dashboard-11313.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dash-unifi-11314
    files:
      - dashboards/unifi/unpoller-dashboard-11314.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dash-unifi-11315
    files:
      - dashboards/unifi/unpoller-dashboard-11315.json
    options:
      labels:
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
