apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - probes/
  - alerts/

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus
    namespace: monitoring
    valuesInline:
      grafana:
        enabled: true
        persistence:
          enabled: true
          size: 10Gi
      prometheus:
        prometheusSpec:
          retention: 15d
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 20Gi
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: monitoring
    valuesFile: loki-stack-values.yaml
  - name: prometheus-blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: blackbox
    namespace: monitoring

