loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 10Gi
    existingClaim: loki-pvc
    storageClassName: "local-path"

promtail:
  enabled: true
  config:
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:1514
          idle_timeout: 60s
          label_structured_data: yes
          labels:
            job: "syslog"
        relabel_configs:
          - source_labels: ['__syslog_message_hostname']
            target_label: 'host'
          - source_labels: ['__syslog_message_app_name']
            target_label: 'app'

  extraPorts:
    syslog-tcp:
      enabled: true
      containerPort: 1514
      protocol: TCP
      service:
        enabled: true
        type: NodePort
        nodePort: 30114
    syslog-udp:
      enabled: true
      containerPort: 1514
      protocol: UDP
      service:
        enabled: true
        type: NodePort
        nodePort: 30115

grafana:
  enabled: false

prometheus:
  enabled: false

fluent-bit:
  enabled: false
