apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpoller
  template:
    metadata:
      labels:
        app: unpoller
    spec:
      containers:
      - name: unpoller
        image: ghcr.io/unpoller/unpoller:latest
        env:
          - name: UP_UNIFI_DEFAULT_URL
            value: "https://unifi-controller:8443"
          - name: UP_UNIFI_DEFAULT_USER
            value: "prometheus"
          - name: UP_UNIFI_DEFAULT_PASS
            value: "changeme"
          - name: UP_PROMETHEUS_HTTP_LISTEN
            value: "0.0.0.0:9130"
        ports:
          - containerPort: 9130
---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 9130
      targetPort: 9130
  selector:
    app: unpoller

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpoller
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: unpoller
  endpoints:
    - port: 9130
      interval: 30s
