apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: "trace_id"
              datasourceUid: "loki" # Allows jumping from metrics to logs
      - name: Loki
        uid: loki
        type: loki
        url: http://loki:3100
        access: proxy
        jsonData:
          derivedFields:
            - datasourceUid: 'prometheus'
              matcherRegex: 'traceId=(\w+)'
              name: 'TraceID'
              url: '$${__value.raw}' # Allows jumping from logs to traces/metrics