adminPassword: admin
service:
  type: ClusterIP
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"
    searchNamespace: ALL
env:
  GF_SERVER_ROOT_URL: "/grafana/"
  GF_SERVER_SERVE_FROM_SUB_PATH: "true"
persistence:
  enabled: true
  type: pvc
  storageClassName: "local-path"
  accessModes: ["ReadWriteOnce"]
  size: 10Gi
  existingClaim: grafana-pvc
podSecurityContext:
  fsGroup: 472
securityContext:
  runAsUser: 472
  runAsGroup: 472
initChownData:
  enabled: false
