grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true
  env:
    GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  persistence:
    enabled: true
    type: pvc
    storageClassName: "local-path"
    accessModes: ["ReadWriteOnce"]
    size: 10Gi
    existingClaim: grafana-pvc
  podSecurityContext:
    fsGroup: 472
  containerSecurityContext:
    runAsUser: 472
    runAsGroup: 472

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "local-path"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    securityContext:
      fsGroup: 65534
      runAsUser: 65534
      runAsGroup: 65534
