apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: websites
  namespace: monitoring
spec:
  interval: 1m
  module: http_2xx
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://www.cloudflare.com
        - https://grafana.com

