# manifests/monitoring/loki-stack-values.yaml
# Values for loki-stack

grafana:
  enabled: false

loki:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi

promtail:
  # Enable the syslog listener port on the promtail daemonset and create a dedicated service for it.
  syslog:
    enabled: true
    port: 1514 # This must match SYSLOG_PORT in vars.sh
    protocol: TCP # Use TCP for syslog

  config:
    snippets:
      # Syslog receiver configuration
      # See: https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#syslog_receiver_config
      extraScrapeConfigs: |
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:1514 # This port must match SYSLOG_PORT in vars.sh
            labels:
              job: syslog
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'
          # With multi-tenancy enabled, Loki will store logs for each host separately.
          # This pipeline stage tells Promtail to set the tenant ID for each log stream
          # to the value of the 'host' label, which we extracted above.
          pipeline_stages:
          - tenant:
              source: 'host'
