{
 "title": "Blackbox Exporter",
 "tags": [ "blackbox" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=~\"(.*blackbox.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Exporter uptime",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"(.*blackbox.*)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory usage of exporter",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=~\"(.*blackbox.*)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of goroutines",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"(.*blackbox.*)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "File descriptor usage",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=~\"(.*blackbox.*)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Probe status",
   "type": "stat",
   "description": "Status of all probes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "Probe duration",
   "type": "graph",
   "description": "Probe duration in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{instance}} ({{job}})" }
   ]
  }
 ]
}