{
 "title": "Node Exporter Full",
 "tags": [ "node-exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "__rate_interval",
    "label": "Rate interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "The average CPU load on the host.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Basic (non-idle)",
   "type": "graph",
   "description": "The average CPU load on the host.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode!=\"idle\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Advanced CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "CPU Advanced",
   "type": "graph",
   "description": "The average CPU load on the host.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Advanced (by mode)",
   "type": "graph",
   "description": "The average CPU load on the host.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, mode) (rate(node_cpu_seconds_total{job=\"node-exporter\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "The memory usage of the host.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",instance=~\"$node\"} - node_memory_MemFree_bytes{job=\"node-exporter\",instance=~\"$node\"} - node_memory_Buffers_bytes{job=\"node-exporter\",instance=~\"$node\"} - node_memory_Cached_bytes{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "description": "The memory usage of the host.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "Disk Space Used %",
   "type": "graph",
   "description": "The disk space usage of the host.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node-exporter\",instance=~\"$node\",fstype!~\"tmpfs|squashfs\"} * 100) / node_filesystem_size_bytes{job=\"node-exporter\",instance=~\"$node\",fstype!~\"tmpfs|squashfs\"})",
     "legendFormat": "{{instance}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Disk I/O Read",
   "type": "graph",
   "description": "The disk I/O usage of the host.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"node-exporter\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O Write",
   "type": "graph",
   "description": "The disk I/O usage of the host.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"node-exporter\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  },
  {
   "title": "Network Traffic Received",
   "type": "graph",
   "description": "The network traffic of the host.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\",instance=~\"$node\",device!~\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Transmitted",
   "type": "graph",
   "description": "The network traffic of the host.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter\",instance=~\"$node\",device!~\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 49 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\",instance=~\"$node\"} - node_boot_time_seconds{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average (1m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average (15m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{job=\"node-exporter\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}